---
title: "BIOL 432 Assignment 3"
author: "Micah GVI"
date: "26/01/2021"
output: html_document
---
### Project Info
**Date**: January 29, 2021
**GitHub**: https://github.com/micahgrubert/BIOL-432-Assignment-3
```{r, include=FALSE}
library(dplyr) #load dplyr package
```


#### Initial Data Wrangling
```{r}
dat<- read.csv("./InputData/FallopiaData.csv") #loading data
dat<-as.data.frame(dat) #convert from list to data.frame

fallo<-filter(dat, Total > 60) #remove rows with Total Biomass <60

fallo1<-select(fallo,Total,Taxon,Scenario,Nutrients) #reorder and remove all other columns

fallo2<- fallo1 %>% mutate(TotalG = Total/1000) %>% #piping to create new column
  select(TotalG,Taxon,Scenario,Nutrients) # continue pipe for replacing and reordering to retain TotalG at front of the df. Could use select(-Total) if order was irrelevant
head(fallo2) #confirm success
```
#### Creating a Custom Function
This function will take two inputs from the user and produce one of four outputs:
```{r}
fallo_counter<-function(X= c(), calc=c("Average", "Sum", "Observations")){ #custom function with variable X, and a series of three possible sting inputs
  if (calc == "Average"){ #when asking for average
    print(mean(X)) # produce a message that gives the avg
  }
  else if (calc == "Sum"){ #when  asking for the sum
    print(sum(X)) #print sum of the vector
  }
  else if (calc == "Observations"){ #when asking for number of observation
    print(length(X)) # print the number of obs (note could use nrow for column, however this would not capture missing lines)
  }
  else{
    cat("Error: Please input a vector and either 'Average', 'Sum,' or 'Observations' separated by a comma") #creates error message if one of the three string inputs is not used
  }
}

```

#### Using the Custom Function
```{r}
fallo_counter(fallo2$Taxon, "Observations") #counts number of observations in the Taxon column
```
```{r}
AvgTotalG<-fallo2 %>% group_by(Nutrients) %>% #pipe to create nutrient groupings
  summarise(avgTotalG=fallo_counter(TotalG,"Average")) #use my custom function to generate output from data created earlier in this pipeline
AvgTotalG #printing table output from pipeline
```

#### Creating a new .csv file
```{r}
write.csv(fallo2,"./Output/WrangledData.csv") #write a CSV containing wrangled data
```




